format = """
[╭](fg:current_line)\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$kubernetes\
$cmd_duration\
$time\
$character\
$line_break\
[╰─](fg:current_line)\
"""

palette = 'dracula'
add_newline = false

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue	= '#6272A4'
cyan = '#8BE9FD'
green	= '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red	= '#FF5555'
yellow = '#F1FA8C'


[kubernetes]
format='(fg:current_line)[](fg:$style)[$symbol$context](bg:$style)[](fg:$style bg:box)[ $namespace](fg:foreground bg:box)[](fg:box)'
disabled = false
symbol = ""
contexts = [
  { context_pattern = ".*staging.*", style = "green"},
  { context_pattern = ".*prod.*", style = "red"},
  { context_pattern = ".*infra.*", style = "orange"},
  { context_pattern = ".*dev.*", style = "blue"},
  { context_pattern = ".*silurien.*", style = "cyan", symbol = "󰙨"},
]

[username]
format = '[─](fg:current_line)[](fg:$style)[](fg:primary bg:$style)[ $user](fg:foreground bg:$style)[](fg:$style bg:box)'
show_always = true
style_root = "cyan"
style_user = "cyan"

[directory]
format = '(fg:pink bg:box)[$read_only](bg:box fg:#FF0000)[ $truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = " ~"
truncation_symbol = ' '
truncation_length = 0
read_only = ' 󱪧'
read_only_style = 'red'
truncate_to_repo = false

[git_branch]
format = '[─](fg:current_line)[](fg:$style)[$symbol](fg:primary bg:$style)[](fg:$style bg:box)[ $branch](fg:foreground bg:box)'
symbol = '󰘬'
style = "yellow"

[git_status]
format = '[ $all_status$ahead_behind](fg:$style bg:box)[](fg:box)'
style = "red"
disabled = false

[git_commit]
format = '[ \( $hash$tag\)](fg:$style bg:box)'
style = "yellow"
disabled = false
tag_disabled = false
only_detached = false
tag_symbol = ' 󰓹 '

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:orange)[](fg:primary bg:orange)[](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[shell]
format = '[─](fg:current_line)[](fg:blue)[ ](fg:primary bg:blue)[](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[](fg:box)'
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
fish_indicator = 'fish'
disabled = true

[time]
format = '[─](fg:current_line)[](fg:purple)[󰥔](fg:primary bg:purple)[](fg:purple bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
disabled = false

[character]
format = '$symbol'
success_symbol = '[](fg:green)'  # L'icône avec un fond de couleur
error_symbol = '[](fg:red)'    # L'icône d'erreur avec un fond de couleur

# detect_files = ['foo'] # can specify filters but wildcards are not supported
# when = ''' test "$HOME" = "$PWD" '''
# format = ' transcending [$output]($style)'